/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TrayIndexRouteImport } from './routes/tray/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as AppHomeRouteImport } from './routes/app/home'
import { Route as AppConfigRouteImport } from './routes/app/config'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TrayIndexRoute = TrayIndexRouteImport.update({
  id: '/tray/',
  path: '/tray/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppConfigRoute = AppConfigRouteImport.update({
  id: '/config',
  path: '/config',
  getParentRoute: () => AppRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/config': typeof AppConfigRoute
  '/app/home': typeof AppHomeRoute
  '/app/': typeof AppIndexRoute
  '/tray': typeof TrayIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/app/config': typeof AppConfigRoute
  '/app/home': typeof AppHomeRoute
  '/app': typeof AppIndexRoute
  '/tray': typeof TrayIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/app/config': typeof AppConfigRoute
  '/app/home': typeof AppHomeRoute
  '/app/': typeof AppIndexRoute
  '/tray/': typeof TrayIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/app' | '/app/config' | '/app/home' | '/app/' | '/tray'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/app/config' | '/app/home' | '/app' | '/tray'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/app/config'
    | '/app/home'
    | '/app/'
    | '/tray/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  TrayIndexRoute: typeof TrayIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tray/': {
      id: '/tray/'
      path: '/tray'
      fullPath: '/tray'
      preLoaderRoute: typeof TrayIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/home': {
      id: '/app/home'
      path: '/home'
      fullPath: '/app/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/config': {
      id: '/app/config'
      path: '/config'
      fullPath: '/app/config'
      preLoaderRoute: typeof AppConfigRouteImport
      parentRoute: typeof AppRouteRoute
    }
  }
}

interface AppRouteRouteChildren {
  AppConfigRoute: typeof AppConfigRoute
  AppHomeRoute: typeof AppHomeRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppConfigRoute: AppConfigRoute,
  AppHomeRoute: AppHomeRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  TrayIndexRoute: TrayIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
